import concurrent.futures
import warnings
from pathlib import Path

import numpy as np
import rasterio
from rasterio.enums import Resampling
from rasterio.io import MemoryFile
from rio_cogeo.cogeo import cog_translate
from rio_cogeo.profiles import cog_profiles
from tqdm import tqdm


def parse_planet_filesystem(root_dir: str | Path) -> dict[int, dict[str, list[Path]]]:
    """Parse the Planet Downloads file structure to get a dict of quads across time"""

    # Mosaic directories: these are per year quarter/month
    mos_dirs = [d for d in Path(root_dir).iterdir() if d.is_dir()]

    # Create dict of directories by year
    year_directories = {}
    for d in mos_dirs:
        year = int(d.name.split("_")[-2][:4])

        if year not in year_directories:
            year_directories[year] = [d]
        else:
            year_directories[year].append(d)

    # Unpack all paths for each year
    year_quads = {}
    for year, dirs in year_directories.items():
        year_paths_quads = []
        for d in dirs:
            year_paths_quads.append([f for f in d.glob("*.tif")])

        year_quads[year] = [quad for sublist in year_paths_quads for quad in sublist]

    # Create a dict of quads per year where each quad is a dict of paths per period.
    year_quads_files = {}
    for year, quad_paths in year_quads.items():
        year_quads = {}
        unique_quads = list({f.stem for f in quad_paths})
        for quad in unique_quads:
            year_quads[quad] = [p for p in quad_paths if p.stem == quad]

        year_quads_files[year] = year_quads

    return year_quads_files


def create_composite(
    list_rasters: list[Path], save_path: str | Path, operation="mean"
) -> None:
    """Create a composite raster from a set of raster images (RGB)

    This function will calculate the mean or median composite of a list of quarterly/monthly
    Planet mosaics and save them as COG (Cloud Optimized GeoTIFF) files using the same
    specifications as the original mosaics. This function assumes the images passed to `list_rasters` are all covering the same extent (i.e. they have the same quad planet ID).

    Parameters
    ----------
    list_rasters : list[Path]
        List of raster images to create the composite from.
    save_path : str | Path
        Path to save the composite raster.
    operation : str, optional
        Operation to perform on the rasters, either "mean" or "median". Default is "mean".

    Returns
    -------
    None
    """

    # Define name of the output file
    unique_name = list({p.stem for p in list_rasters})

    if len(unique_name) > 1:
        warnings.warn(
            f"Multiple unique names found in the list of rasters: {unique_name}. "
            "Using the first one for the output file name."
        )

    unique_name = unique_name[0]

    bbox: list = []

    arr_agg: list[np.ndarray] = []
    arr_meta: list[dict] = []
    for idx, quad in enumerate(list_rasters):
        with rasterio.open(quad, "r") as src:
            if idx == 0:
                bbox = list(src.bounds)
            elif idx > 0 and bbox == list(src.bounds):
                bbox = list(src.bounds)
            else:
                raise ValueError(
                    f"All rasters must cover the same extent. Raster {quad} has different bounds: {src.bounds} compared to {bbox}"
                )

            # Take all the bands. We default to only take RGB for composites.
            arr = src.read()
            arr_agg.append(arr)
            arr_meta.append(src.profile)

    # Stack the arrays and calculate the mean or median
    if operation == "mean":
        arr = np.mean(np.stack(arr_agg, axis=0), axis=0)
    elif operation == "median":
        arr = np.median(np.stack(arr_agg, axis=0), axis=0)
    else:
        raise ValueError(
            f"Operation must be either 'mean' or 'median', not {operation}"
        )

    # Take only RGB
    arr = arr[0:3, :, :]

    with MemoryFile() as memfile:
        # Re-write the new dtype
        meta = arr_meta[0]
        meta.update({"dtype": arr.dtype, "count": arr.shape[0]})

        with memfile.open(**arr_meta[0]) as mem:
            mem.write(arr)

            dst_profile = cog_profiles.get("deflate")
            cog_translate(
                mem,
                f"{save_path}/{unique_name}_composite.tif",
                dst_profile,
                in_memory=True,
                quiet=True,
            )


def process_composites_parallel(
    dict_paths: dict[int, dict[str, list[Path]]],
    save_dir: str,
    operation="mean",
    nthreads: int = 4,
) -> None:
    """
    Process composites in parallel for each quad in the dictionary.

    Parameters
    ----------
    d : dict[int, dict[str, list[Path]]]
        Dictionary generated by `parse_planet_filesystem`.
    save_dir : str
        Directory to save the composite files.
    operation : str, optional
        Operation to perform on the rasters, either "mean" or "median". Default is "mean".

    Returns
    -------
    None
    """

    # Create save directory if it doesn't exist
    save_dir = Path(save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)

    for year, quads in dict_paths.items():
        # Add a year folder to the save dir
        year_save_dir = save_dir / str(year)
        year_save_dir.mkdir(parents=True, exist_ok=True)

        def process_quad(quad_name: str, quad_paths: list[Path]) -> None:
            """Process a single quad by creating a composite."""
            create_composite(quad_paths, year_save_dir, operation)

        tasks = [(quad_name, quad_paths) for quad_name, quad_paths in quads.items()]

        with tqdm(
            total=len(tasks), desc=f"Processing quads {year} -> composites"
        ) as pbar:
            # Use ThreadPoolExecutor for parallel processing
            with concurrent.futures.ThreadPoolExecutor(nthreads) as executor:
                futures = [
                    executor.submit(process_quad, quad_name, quad_paths)
                    for quad_name, quad_paths in tasks
                ]

                # Wait for all tasks to complete
                for future in concurrent.futures.as_completed(futures):
                    future.result()
                    pbar.update(1)

    return None


def resample_resolution(
    input_path: Path, output_path: Path, target_resolution: float
) -> None:
    """
    Resample a raster to a new resolution.

    Parameters
    ----------
    input_path : Path
        Path to the input raster file.
    output_path : Path
        Path to the output raster file.
    target_resolution : float
        Target resolution in the same units as the input raster.

    Returns
    -------
    None
    """

    # Let's assume equal resolution (square!)
    xres, yres = (
        target_resolution,
        target_resolution,
    )

    with rasterio.open(input_path, "r") as dataset:
        scale_factor_x = dataset.res[0] / xres
        scale_factor_y = dataset.res[1] / yres

        profile = dataset.profile.copy()
        # resample data to target shape
        data = dataset.read(
            out_shape=(
                dataset.count,
                int(dataset.height * scale_factor_y),
                int(dataset.width * scale_factor_x),
            ),
            resampling=Resampling.bilinear,
        )

        # scale image transform
        transform = dataset.transform * dataset.transform.scale(
            (1 / scale_factor_x), (1 / scale_factor_y)
        )
        profile.update(
            {
                "height": data.shape[-2],
                "width": data.shape[-1],
                "transform": transform,
            }
        )

    with rasterio.open(output_path, "w", **profile) as dataset:
        dataset.write(data)

    return None


def resample_resolution_parallel(
    path_rasters: str | Path,
    path_save_rasters: str | Path,
    target_resolution: float,
    nthreads: int,
) -> None:
    """Process the resample resolution function in parallel

    Execute the resample_resolution function for each raster in parallel using
    a list of GeoTIFFs and saving them using the same name in another folder.

    Parameters:
    -----------
    path_rasters : list[Path]
        List of input raster file paths.
    path_save_rasters : Path
        Directory to save the output raster files.
    target_resolution : float
        Target resolution for the output rasters.
    nthreads : int
        Number of threads to use for parallel processing.

    Returns:
    --------
        None

    """
    with concurrent.futures.ProcessPoolExecutor(max_workers=nthreads) as executor:
        futures = []
        for input_raster in path_rasters:
            output_raster = path_save_rasters / input_raster.name
            futures.append(
                executor.submit(
                    resample_resolution, input_raster, output_raster, target_resolution
                )
            )

        for future in concurrent.futures.as_completed(futures):
            future.result()

    return None
